### ISSUE TITLE
Random numbers for Linux should poll `/dev/random` once

### ISSUE THREAD

**Issue by 05nelsonm** [whyoleg/cryptography-kotlin#1]
For the linux implementation of `PlatformRandom` it should poll `/dev/random` once and only once before attempting to retrieve bytes from `/dev/urandom` to ensure it is properly seeded. This was an issue with `SecureRandom` on Android for API 1-18 which caused some mayhem.

https://android-developers.googleblog.com/2013/08/some-securerandom-thoughts.html

Can see my implementation for pointers https://github.com/05nelsonm/secure-random/blob/master/secure-random/src/linuxAndroidMain/kotlin/io/matthewnelson/secure/random/internal/URandom.kt

**Comment by whyoleg** [comment]
Thanks for pointing this!
But, I'm not sure, that link you've posted is what we need to do. The issue in blog post is regarding requiring of initialisation of JCA SecureRandom with values from urandom. We don't have anything like this.
But, I've read more info about random/urandom and from what I've found: urandom provides enough entropy by default for short-living operations and is seeded enough after boot.
So IMO, what is needed, is to leave current approach, but provide additional API to force reseeding random for long-living operations like when generating certificates (which is not availability at the moment)

WDYT?

**Comment by 05nelsonm** [comment]
Imo reseeding is unnecessary. Can see how [rust-random](https://github.com/rust-random/getrandom/blob/41b89814e332aa20e8916579f95762de784d6b4b/src/use_file.rs#L87) has it implemented (polling `/dev/random` once to ensure `/dev/urandom` has been seeded).

[getrandom](https://man7.org/linux/man-pages/man2/getrandom.2.html) does it this way (polling `/dev/random` once), but requires a `syscall` and check if it's available.

**Comment by whyoleg** [comment]
Im now thinking - may be just drop `urandom` support at all and use `getrandom` all the time. It was introduced in linux kern el 3.17 (2014!).
does it really make sense to support fallback?

**Comment by 05nelsonm** [comment]
It **definitely** still makes sense to support `/dev/urandom` fallback in the absence of `getrandom` support. Never know how your library will be utilized in other projects and for what purpose.

**Comment by 05nelsonm** [comment]
Thought of a scenario where supporting fallback to `/dev/urandom` would be necessary. If you plan to also support Android Native. Most manufacturers only provide 2 years of updates, and there are a TON of devices running old versions which do not have `getrandom` available.

**Comment by whyoleg** [comment]
fixed in https://github.com/whyoleg/cryptography-kotlin/commit/3e6e004ea0f9ab5c1f2f052e88dd4111ee5c5bd7 (forgot to link issue in commit...)
Thx for pointing!
