### ISSUE TITLE
Linux random numbers may not fill array completely

### ISSUE THREAD

**Issue by 05nelsonm** [whyoleg/cryptography-kotlin#2]
Current Linux implementation for `PlatformRandom` only checks for an error, but does not check if the number returned (the number of bytes retrieved from `/dev/urandom`) filled the `ByteArray` completely.

See [fillCompletely](https://github.com/05nelsonm/secure-random/blob/504e2ae058ca77c68b85142ef054ab837a643ed4/secure-random/src/linuxAndroidMain/kotlin/io/matthewnelson/secure/random/internal/-LinuxAndroidPlatform.kt#L32)

And [fillCompletelyUsage](https://github.com/05nelsonm/secure-random/blob/504e2ae058ca77c68b85142ef054ab837a643ed4/secure-random/src/linuxAndroidMain/kotlin/io/matthewnelson/secure/random/internal/URandom.kt#L61)

for pointers

**Comment by whyoleg** [comment]
Thanks!

Will fix it
Do you have any idea on how to properly test it?

**Comment by 05nelsonm** [comment]
> Do you have any idea on how to properly test it?

I just tested the `fillCompletely` extension function [HERE](https://github.com/05nelsonm/secure-random/blob/master/secure-random/src/linuxAndroidTest/kotlin/io/matthewnelson/secure/random/internal/FillCompletelyUnitTest.kt) and of course the actual implementation to ensure the `ByteArray` was actually filled with non-empty values within a certain threshold (b/c some indices will still remain empty) [HERE](https://github.com/05nelsonm/secure-random/blob/504e2ae058ca77c68b85142ef054ab837a643ed4/secure-random/src/commonTest/kotlin/io/matthewnelson/secure/random/EnsureFilledHelper.kt#L29)

**Comment by whyoleg** [comment]
fixed in https://github.com/whyoleg/cryptography-kotlin/commit/3e6e004ea0f9ab5c1f2f052e88dd4111ee5c5bd7

Real stress test was added in https://github.com/whyoleg/cryptography-kotlin/commit/6d596b5951bacbe80eb9bd7aa0a0fe830b5ac406

Thx for findings!
