### ISSUE TITLE
Can I set my PublicKey in "provider.get(RSA.PSS)" ?

### ISSUE THREAD

**Issue by thanhhoai162963** [whyoleg/cryptography-kotlin#23]
val ecdsa = provider.get(ECDSA)
val keyPairGenerator = ecdsa.keyPairGenerator(EC.Curve.P521)
val keyPair: ECDSA.KeyPair = keyPairGenerator.generateKey()

I wasn't found setPublicKey()

**Comment by whyoleg** [comment]
Hey, Im not sure what do you mean by `setPublicKey`. What use case do you have? What are you trying to do?

**Comment by thanhhoai162963** [comment]
I use asymmetric encryption which connect resful api. I get rsaPublicKey from api server (not need encryption). 
After I need set publickKey with rsaPublicKey and key random from local to encrypt(k) call api.

Example: 
fun encryptData(dataDes: String): String? {
        return try {
            val c = Cipher.getInstance(Algorithm.RSA_OAEP)
            c.init(Cipher.ENCRYPT_MODE, Key.rsaPublicKey())
            val encryptOut = c.doFinal(dataDes.toByteArray())
            org.bouncycastle.util.encoders.Base64.toBase64String(encryptOut)
        } catch (e: Exception) {
            Log.d("error:", "error")
            ""
        }
    }

**Comment by whyoleg** [comment]
As far as I understand you need to decode key from binary representation and then use it. In this case you will need something like:
ECDSA:
```kotlin
val ecdsa = provider.get(ECDSA)
val publicKey = ecdsa.publicKeyDecoder(EC.Curve.P521).decodeFrom(EC.PublicKey.Format.RAW, keyByteArray) // or other format
// and then do anything with key verify or encrypt
```
Similar for RSA-OAEP:
```kotlin
val rsa = provider.get(RSA.OAEP)
val publicKey = rsa.publicKeyDecoder(SHA256).decodeFrom(RSA.PublicKey.Format.DER) // or other format
// and then do anything with key verify or encrypt
```
Does it helps?

**Comment by thanhhoai162963** [comment]
val publicKey = rsa.publicKeyDecoder(SHA256).decodeFrom(RSA.PublicKey.Format.DER, **myKey**) 
 //Follow I understand, Can I set publicKey = "myKey" here?

**Comment by whyoleg** [comment]
> Follow I understand, Can I set publicKey = "myKey" here?

Yeah, though, `myKey` should be a `ByteArray`, not a `String`. DER format is the same format which is used in JDK APIs by default for RSA keys.

**Comment by thanhhoai162963** [comment]
fun encryptData(dataRandom: String): String? {
        return try {
            val c = Cipher.getInstance("RSA/ECB/OAEPPadding")
            c.init(Cipher.ENCRYPT_MODE, loadPublicKey())
            val encryptOut = c.doFinal(dataRandom.toByteArray())
            org.bouncycastle.util.encoders.Base64.toBase64String(encryptOut)
        } catch (e: Exception) {
            Log.d("error:", "error")
            ""
        }
    }
    
      @Throws(GeneralSecurityException::class, IOException::class)
    private fun loadPublicKey(): PublicKey? {
        val rsaPublicKey = runBlocking {
            LizAiDataStore.instance.getRsaPublicKey()?.publicKey
        }
        val data = Base64.decode(rsaPublicKey)
        val spec = X509EncodedKeySpec(data)
        val fact = KeyFactory.getInstance(Algorithm.RSA)
        return fact.generatePublic(spec)
    }
    
    Thanks you very much recommend you @whyoleg  , after 3 days thinking, learn about
from website, I still can't convert this code.

**Comment by thanhhoai162963** [comment]
Thank you @whyoleg. I generated encryptOut. But my server not decrypt . My server use dot Net rsa oeap follow:
[https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsacryptoserviceprovider?view=netcore-3.1](url)
keySize: 2048

**Comment by whyoleg** [comment]
Looks like .NET is using RSA OAEP with SHA1 - hint on SO: https://stackoverflow.com/a/67793433
So you need to try `publicKeyDecoder(SHA1)` instead

**Comment by thanhhoai162963** [comment]
Thanks you very much @whyoleg , it working. Special thanks.

**Comment by whyoleg** [comment]
Cool! I'm closing an issue! JDK to cryptography-kotlin guide will be tracked in #24
