### ISSUE TITLE
Can I signatureVerifier RSA OAEP ?

### ISSUE THREAD

**Issue by thanhhoai162963** [whyoleg/cryptography-kotlin#25]
Can I signatureVerifier the same as ECDSA for RSA OAEP ?
Example:
val verificationResult: Boolean =
    keyPair.publicKey.signatureVerifier(digest = SHA512).verifySignature("text1".encodeToByteArray(), signature)

**Comment by whyoleg** [comment]
Hey, ECDSA provides `signatureVerifier`, so yes, API is similar to what RSA PSS has (RSA OAEP is for encryption, not signature verification)
Which specific issue do you have, or what do you want to do in the end?
