### ISSUE TITLE
RSA/ECB/PKCS1Padding

### ISSUE THREAD

**Issue by chandrakant-kshirsagar** [whyoleg/cryptography-kotlin#29]
@whyoleg How to use the below code here.

 Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");

**Comment by whyoleg** [comment]
Hey! Sorry, but RSA with PKCS1 encryption is not yet supported. Only RSA OAEP is supported for now.

Could you please describe why do you need this specific algorithm? Is it needed to community with some old software? I'm asking this, because generally, RSA with PKCS1 encryption is not supposed to be used for new applications, so that's why I delayed adding it, providing more robust algorithms first.

**Comment by FutureExDev** [comment]
@whyoleg thanks for the information.

Currently, I am converting my old code to compose-multiplatform, which uses **RSA/ECB/PKCS1Padding** encryption. Should I migrate my code to **RSA OAEP** or is there any further plan for **RSA with PKCS1?**

**Comment by whyoleg** [comment]
Yeah, if you control server part and so could use RSA OAEP for your use case - then it's better to do it. RSA with PKCS1 encryption probable will be supported in upcoming release, but there is no date yet - may be in a couple of months - hard to predict my workload right now.

**Comment by FutureExDev** [comment]
@whyoleg I will discuss with my backend team about changing the encryption to RSA OAEP. Thank you for your support.👍

**Comment by e9ab98e991ab** [comment]
import java.security.KeyFactory
import java.security.spec.X509EncodedKeySpec
import android.util.Base64;
import javax.crypto.Cipher 
actual object RSAUtils {
    @OptIn(ExperimentalEncodingApi::class)
    actual fun encryptData(str: String, key: String): String {
        // 将文本格式的公钥解码为 PublicKey 对象
        val keyBytes = Base64.decode(key,Base64.NO_WRAP)
        val pubKeySpec = X509EncodedKeySpec(keyBytes)
        val keyFactory = KeyFactory.getInstance("RSA")
        val pubKey = keyFactory.generatePublic(pubKeySpec)

        // 使用公钥对文本加密
        val cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding")
        cipher.init(Cipher.ENCRYPT_MODE, pubKey)
        val encryptedBytes = cipher.doFinal(str.toByteArray())
        return Base64.encodeToString(encryptedBytes,Base64.NO_WRAP)
    } 
}

Android is implemented in KMM. I don't know how to write iOS. The hard author wrote the code of iOS and merged into the library

**Comment by ivanpataki** [comment]
Hi,
Plus one here, unfortunately I cannot change the server side encryption, so looking forward to 0.4.0!
Thanks!

**Comment by jvondermarck** [comment]
I would also have the use case to use AES **ECB** encryption for an old app that cannot be migrated to a safer encryption. So it would be great in the future to implement it.

**Comment by whyoleg** [comment]
AES.ECB, RSA.RAW (jdk: RSA/ECB/NoPadding) and RSA.PKCS1 encryption (RSA/ECB/PKCS1Padding) are available in `main` branch and so in 0.4.0 snapshots. No date for release yet as I need to finish other things.
API is a bit clattered for those legacy RSA algorithms (e.g digest is required, but is not used). It will be definitely changed before 1.0 someday.

**Comment by whyoleg** [comment]
[0.4.0 was just released!](https://github.com/whyoleg/cryptography-kotlin/releases/tag/0.4.0)
RSA encryption with [PKCS1 padding](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-r-s-a/-p-k-c-s1/-private-key/index.html) and [without padding](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-r-s-a/-r-a-w/index.html) are available now.

**Comment by whyoleg** [comment]
@mpiffari, I'm afraid there is only [tests code](https://github.com/whyoleg/cryptography-kotlin/blob/715dbd0f8d8c7b128ae3305ebdd2d2c75cfe74f1/cryptography-providers-tests/src/commonMain/kotlin/default/RsaPkcs1Test.kt#L44-L71).

Overall, the API is very similar to [AES](https://whyoleg.github.io/cryptography-kotlin/examples/#aes-gcm), the only difference is key generation:
```kotlin
/*technically speaking, any digest could be provided here, as it's not used - the API will be fixed in future*/
// to generate key
CryptographyProvider.Default.get(RSA.PKCS1)
    .keyPairGenerator(keySize, SHA1)
    .generateKey()
    .privateKey

// to decode key
val privateKey = CryptographyProvider.Default.get(RSA.PKCS1)
    .privateKeyDecoder(SHA1)
    .decodeFromByteArray(RSA.PrivateKey.Format.PEM, TODO("bytes"))

// to use key
privateKey.decryptor().decrypt(TODO("ciphertext here"))
```

I'm planning to add more samples for each algorithm in future.

**Comment by chandrakantkshirsagar-wq** [comment]
@whyoleg Great 👍 , Now, I can **encrypt/decrypt** data using RSA / PKCS1 the code below. 

`suspend fun encrypt(plainText: String, publicKey: String): String {
     val publicKeyBytes = Base64.decode(publicKey)

        val publicKey = CryptographyProvider.Default
            .get(RSA.PKCS1)
            .publicKeyDecoder(SHA1)
            .decodeFromByteArray(RSA.PublicKey.Format.DER, publicKeyBytes)
        val cipherTextBytes = publicKey.encryptor().encrypt(plainText.toByteArray())
        return Base64.encode(cipherTextBytes)
    }

    @OptIn(DelicateCryptographyApi::class)
    suspend fun decrypt(plainText: String, privateKey: String): String {
        val privateKeyBytes = privateKey.toByteArray()
        val publicKey = CryptographyProvider.Default.get(RSA.PKCS1).privateKeyDecoder(SHA1)
            .decodeFromByteArray(RSA.PrivateKey.Format.DER, privateKeyBytes)

        val cipherTextBytes =
            publicKey.decryptor().decrypt(plainText.toByteArray()).decodeToString()
        return cipherTextBytes
    }`


It works on Android, Desktop, and iOS, but on the Web, it shows the error below.

```
IllegalStateException: RSA-PKCS1 encryption is not supported by WebCrypto
```

**Comment by chandrakantkshirsagar-wq** [comment]
@whyoleg, I tried the code below 

>     <script src="https://cdn.jsdelivr.net/npm/node-forge@1.3.1/dist/forge.min.js"></script>
>     <script>
>         function formatPem(publicKey) {
>           if (publicKey.includes("BEGIN PUBLIC KEY")) return publicKey; // already PEM
>           // Wrap Base64 into proper PEM format
>           const lines = publicKey.match(/.{1,64}/g).join("\n");
>           return  `-----BEGIN PUBLIC KEY-----\n${lines}\n-----END PUBLIC KEY-----`;
>         }
> 
>         function encryptPKCS1WithKey(message, publicKey) {
>           try {
>             const pem = formatPem(publicKey);
>             const pubKey = forge.pki.publicKeyFromPem(pem);
>             const encrypted = pubKey.encrypt(message, 'RSAES-PKCS1-V1_5');
>             return forge.util.encode64(encrypted);
>           } catch (e) {
>             console.error("Error in encryptPKCS1WithKey:", e);
>             throw e;
>           }
>         }
> 
>         window.encryptPKCS1WithKey = encryptPKCS1WithKey;
>     </script>
> 
> 
>     @JsName("encryptPKCS1WithKey")
>     external fun encryptPKCS1WithKey(message: String, publicKeyPem: String): String
> 
> 
>      actual suspend fun encryptData(data: String, publicKey: String): String {
>      try {
>     
>         return encryptPKCS1WithKey(data,publicKey)
>      }catch (e: Exception){
>     
>         return ""
>     }
>    }

It works locally, but I can't deploy it to production. Is there any other way we can implement this code securely?

**Comment by whyoleg** [comment]
> Is there any other way we can implement this code securely?

I don't know about the good and easy way to do it.

Are you sure that you need to use RSA encryption with PKCS1 padding?
It's for sure better to switch to something else if you want your app to be secure.
