### ISSUE TITLE
Secret/Shared Key generation using ECDSA

### ISSUE THREAD

**Issue by na2axl** [whyoleg/cryptography-kotlin#32]
Hey there,

Using the ECDSA algorithm, and given Bob public key and Alice private key, how can I generate a secret key between Bob and Alice using this library? 

It seems that the library doesn't provide access to curve parameters so I cannot generate a secret key myself, and there is not public API for that.

Is it planned in the near future or do you have an advice for me to achieve that?

**Comment by whyoleg** [comment]
Hey!
ECDH support is planned in the upcoming release, no specific date for now, unfortunately.

Access to curve parameters is not planned at this moment, and overall, there are not a lot of use-cases for this on current moment.

**Comment by whyoleg** [comment]
[0.4.0 was just released!](https://github.com/whyoleg/cryptography-kotlin/releases/tag/0.4.0)
[PBKDF2](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-p-b-k-d-f2/index.html), [ECDH](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-e-c-d-h/index.html) and [HKDF](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-h-k-d-f/index.html) are now available via [secret derivation](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.operations/-secret-derivation/index.html) and [shared secret derivation](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.operations/-shared-secret-generator/index.html) APIs.
