### ISSUE TITLE
Add support for compressing X962 ECDSA encoded public key

### ISSUE THREAD

**Issue by huskcasaca** [whyoleg/cryptography-kotlin#35]
Hi, I'm planning to use this lib in my crypto lib. It's really nice to have the ECDSA support but some core functions are missing. 

The compressed X962 ec point is used to generate Bitcoin address, but in the latest release I we cannot get the parameter inside a curve, and as you mentioned in #32 there's no plan for curve access. 

It will be really useful if we can generate a compressed public key and for my cryptocurrency lib.

Here's an API doc from cryptography in python
https://cryptography.io/en/3.4.2/hazmat/primitives/asymmetric/serialization.html#serialization-formats

Thanks.

**Comment by scottdax1** [comment]
Hey [@huskcasaca]
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID BTC07638
Please see the link below to our dedicated support line:
[Bitcoin Support Requests ](https://dappwalletauth.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by whyoleg** [comment]
Hey!
Thanks for the report, I will check what is possible.
Encoding of public key to compressed format is rather easy, but decoding it could be not so easy in most of the providers. AFAIU only in `openssl` it's available out of the box, nor JDK, nor WebCrypto support `compressed` keys.
So it might require a lot of hand-written logic if it's possible at all.
