### ISSUE TITLE
HKDF and/or PBKDF2 support for generating AES keys

### ISSUE THREAD

**Issue by Wavesonics** [whyoleg/cryptography-kotlin#47]
The ability to provide a client and server secret to generate a key would be very helpful.

Some pseudo code:
```
    shared_secret = server_secret + client_secret

    hkdf = HKDF(
        algorithm=SHA256(),
        length=key_length,
        salt=salt,
    )
    
    aes_key = hkdf.derive(shared_secret)
```

**Comment by whyoleg** [comment]
[0.4.0 was just released!](https://github.com/whyoleg/cryptography-kotlin/releases/tag/0.4.0)
[PBKDF2](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-p-b-k-d-f2/index.html), [ECDH](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-e-c-d-h/index.html) and [HKDF](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-h-k-d-f/index.html) are now available via [secret derivation](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.operations/-secret-derivation/index.html) and [shared secret derivation](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.operations/-shared-secret-generator/index.html) APIs.

**Comment by Wavesonics** [comment]
amazing, that was fast!
